//stats [hp, en, mob, arm]
//upgrade [#hp, #en, #mob, #arm]

/*
  var blank = {
    name: "",
    stats: [],
    upgrade: [],
    move: ,
    type: "",
    terrain: "",
    size: "",
    wpSpace: ,
    partSlots: ,
    fub: "",
    abilities: [],
    iWeapons: [],
    weapons: []
  };
*/

var battleships = {
  Shirogane: {
    name: "Shirogane",
    stats: [14000, 200, 60, 1200],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    fub: "Armor +20%",
    wpSpace: 10,
    partSlots: 2,
    abilities: ["EN Regen (L)", "E Field"],
    iWeapons: ["AA Autocannon", "Spider Net", "Weaponbreaker", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon"],
    weapons: []
  },
  Hagane_Shiro: {
    name: "Hagane (Shiro Type)",
    stats: [14000, 200, 60, 1200],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field"],
    iWeapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon"],
    weapons: []
  },
  Hagane: {
    name: "Hagane",
    stats: [15000,220,60,1230],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field'"],
    iWeapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Sub Cannon", "Impact Cannon", "Tronium Cannon"],
    weapons: []
  },
  Kurogane: {
    name: "Kurogane",
    stats: [16000, 220, 65, 1500],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr/UndGnd",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field"],
    iWeapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon", "Titanic Drill"],
    weapons: []
  },
  Hiyru_Custom: {
    name: "Hiryu Custom",
    stats: [14000, 210, 65, 1300],
    upgrade: [4,6,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "ABAS",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Weapon Accuracy +20%",
    abilities: ["E Field"],
    iWeapons: ["AA Autocannon", "Homing Missile", "Long Range Missile", "Dual Beam Cannon", "Gravity Cannon"],
    weapons: []
  }
}

var ptx = {
  Gespenst_Kai: {
    name: "Gespenst MKII-M (Kai)",
    stats: [3700, 100, 100, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd/Wtr",
    terrain: "AAAA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "All Terrains (except Air) S",
    abilities: [],
    iWeapons: ["Split Missile", "Jet Magnum"],
    weapons: ["M95 Machine Gun", "Plasma Slicer"]
  },
  Gespenst_Katina: {
    name: "Gespenst MKII-M (Katina)",
    stats: [3700, 100, 95, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "Armor and HP +15%",
    abilities: [],
    iWeapons: ["Split Missile", "Jet Magnum"],
    weapons: ["Plasma Slicer", "M13 Shotgun"]
  },
  Gespenst_Russel: {
    name: "Gespenst MKII-M (Russel)",
    stats: [3800, 100, 95, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "Armor +20%",
    abilities: [],
    iWeapons: ["Split Missile", "Jet Magnum"],
    weapons: ["M95 Machine Gun", "Plasma Slicer"]
  },
  Gespenst_R: {
    name: "Gespenst MkII-R",
    stats: [3700, 120, 110, 1200],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 180,
    partSlots: 4,
    fub: "Mobility +15% and HP +20%",
    abilities: ["Beam Coat"],
    iWeapons: ["Split Missile"],
    weapons: ["Plasma Cutter", "Chakram Caster", "Slash Ripper", "Double Magna Rifle", "Graviton Cannon"]
  },
  Gespenst_S: {
    name: "Gespenst MkII-S",
    stats: [4400, 200, 105, 1700],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Air/Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "HP +20% and EN +15%",
    abilities: ["AB Field"],
    iWeapons: ["Split Missile", "Mega Blaster", "Yell! Gespenst Kick!"],
    weapons: []
  },
  Gespenst: {
    name: "Gespenst",
    stats: [3600, 140, 110, 1200],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Air/Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "I Weapon Ammo +4",
    abilities: ["Beam Coat"],
    iWeapons: ["Split Missile", "Neutron Beam"],
    weapons: ["Weapon Breaker", "Plasma Slicer", "Rectangle Launcher", "Remote Slasher", "M90 Assault Machine Gun"]
  },
  Alteisen: {
    name: "Alteisen",
    stats: [4500, 110, 95, 1600],
    upgrade: [6,8,8,7],
    move: 6,
    type: "Grd/Wtr",
    terrain: "ASAA",
    size: "M",
    wpSpace: 90,
    partSlots: 2,
    fub: "All Weapon Terrains S",
    abilities: ["Beam Coat"],
    iWeapons: ["Autocannon", "Heat Horn", "Revolver Stake", "Heavy Claymore", '"Trump Card"'],
    weapons: []
  },
  Alteisen_Riese: {
    name: "Alteisen Riese",
    stats: [6929, 130, 110, 1911],
    upgrade: [6, 8, 8, 7],
    move: 7,
    type: "Grd/Wtr",
    terrain: "ASAS",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "All Weapon Terrains S",
    abilities: ["Beam Coat"],
    iWeapons: ["5-Barrel Machine Cannon", "Plasma Horn", "Revolving Bunker", "Avalanche Claymore", "Aerial Claymore"],
    weapons: []
  },
  Weissritter: {
    name: "Wiessritter",
    stats: [4100, 120, 115, 900],
    upgrade: [8,8,5,10],
    move: 7,
    type: "Air/Grd",
    terrain: "AACS",
    size: "M",
    wpSpace: 90,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: ["Beam Coat"],
    iWeapons: ["Split Missile", "Beam Cannon", "Oxtongue Rifle E", "Oxtongue Rifile B", "Oxtongue Rifile W"],
    weapons: ["Plasma Slicer"]
  },
  Rein_Weissritter: {
    name: "Rein Weissritter",
    stats: [5100, 140, 125, 1100],
    upgrade: [8,8,5,10],
    move: 8,
    type: "Air/Grd",
    terrain: "SACS",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: ["Beam Coat", "HP Regen (S)"],
    iWeapons: ["Split Missile", "3-Barrel Beam Cannon", "Howling Launcher E", "Howling Launher B", "Howling Launher X"],
    weapons: []
  },
  Schutzwald: {
    name: "Schutzwald",
    stats: [4400, 150, 85, 1600],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd/Wtr",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "AB Field",
    abilities: [],
    iWeapons: ["Gatling Gun", "Autocannon", "Twin Geam Cannon"],
    weapons: ["Plasma Sliver", "G-Railgun"]
  },
  R_Blade: {
    name: "R-Blade",
    stats: [3500, 120, 115, 1200],
    upgrade: [7,8,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "W Space +30",
    abilities: [],
    iWeapons: ["Gatling Gun", "Blade Tonfa"],
    weapons: ["G-Revolver", "G-Railgun"]
  },
  Wildwurger: {
    name: "Wildwurger",
    stats: [4200, 150, 120, 1600],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 110,
    partSlots: 2,
    fub: "Mobility and Armor +15%",
    abilities: [],
    iWeapons: ["3-Barrel Gatling Cannon", "Cold Metal Sword", "Stag Beetle Crusher", "Raptor Wings"],
    weapons: ["M90 Assault Machine Gun"]
  },
  Wildwurger_L: {
    name: "Wildwurger-L",
    stats: [4200, 150, 120, 1600],
    upgrade: [10,10,10,10],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 140,
    partSlots: 3,
    fub: "Mobility and Armor +15%",
    abilities: [],
    iWeapons: ["Stun Shock", "3-Barrel Gatling Cannon", "M90 Assault Machine Gun", "Cold Metal Sword", "Stag Beetle Crusher", "Raptor Wings"],
    weapons: []
  },
  Wildfalken: {
    name: "Wildfalken",
    stats: [4000, 140, 130, 1100],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: [],
    iWeapons: ["Gatling Gun", "Split Missile", "Oxtongue Rifle E", "Oxtongue Rifle B", "Oxtongue Rifle W"],
    weapons: ["Roche Saber"]
  }
};

var rtx = {
  Huckebein_II: {
    name: "Huckebein MKII",
    stats: [4000, 130, 115, 1200],
    upgrade: [8,9,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 3,
    fub: "W Space +50",
    abilities: ["G Wall"],
    iWeapons: ["Gatling Gun", "G-Impact Cannon"],
    weapons: ["Beam Sword" , "Photon Rifle", "Chakram Caster"]
  },
  Huckebein_IIM: {
    name: "Huckebein MkII-M",
    stats: [4000, 130, 115, 1200],
    upgrade: [8,9,6,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 3,
    fub: "W Space +30",
    abilities: [],
    iWeapons: ["Gatling Gun"],
    weapons: ["Beam Sword", "Photon Rifle", "Rectangle Launcher"]
  },
  Huckebein: {
    name: "Huckebein",
    stats: [3900, 150, 120, 1200],
    upgrade: [8,10,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 120,
    partSlots: 2,
    fub: "W Space +40 and EN +20%",
    abilities: ["AB Field", "Double Image"],
    iWeapons: ["Gatling Gun", "Black Hole Cannon"],
    weapons: ["Roche Saber", "Magna Beam Rifile", "Remote Slasher"]
  },
  Huckebein_III_L: {
    name: "Huckebein MIII-L",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    iWeapons: ["Gatling Gun", "Multi-Trace Missiles", "Fang Slasher", "Graviton Rifle"],
    weapons: ["Roche Saber"]
  },
  Huckebein_III_T: {
    name: "Huckebeing MIII-T",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AAAA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    iWeapons: ["Gatling Gun", "Fang Slasher", "Graviton Rifle"],
    weapons: ["Roche Saber", "Remote Slasher", "Boosted Rifle"]
  },
  Huckebein_III_R: {
    name: "Huckebein MIII-R",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AAAA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    iWeapons: ["Gatling Gun", "Multitrace Missile", "Fang Slasher", "Graviton Rifile"],
    weapons: ["Photon Rifle, Roche Saber, Remote Slasher, Boosted Rifle"]
  },
  Huckebein_Gunner_L: {
    name: "Huckebein Gunner-L",
    stats: [4800, 180, 130, 1300],
    upgrade: [7,7,5,9],
    move: 9,
    type: "Air",
    terrain: "SABS",
    size: "M",
    wpSpace: 0,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory"],
    iWeapons: ["Gatling Gun", "Multi-Trace Missile", "Rip Missile", "Graviton Rifle", "Full Impact Cannon"],
    weapons: []
  },
  Huckebein_Gunner_R: {
    name: "Huckebein Gunner-R",
    stats: [4800, 180, 130, 1300],
    upgrade: [7,7,5,9],
    move: 9,
    type: "Air",
    terrain: "SABS",
    size: "M",
    wpSpace: 0,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory"],
    iWeapons: ["Gatling Gun", "Multi-Trace Missile", "Rip Missile", "Graviton Rifle", "Full Impact Cannon"],
    weapons: []
  },
  Huckebein_Boxer_L: {
    name: "Huckebein Boxer-L",
    stats: [5700, 249, 125, 1955],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Grd/Wtr",
    terrain: "ASBS",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    iWeapons: ["Gatling Gun", "Graviton Cannon", "Fang Slasher", "Geist Knuckle", "G-Sword Diver"],
    weapons: []
  },
  Huckebein_Boxer_R: {
    name: "Huckebein Boxer-R",
    stats: [5700, 249, 125, 1955],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Grd/Wtr",
    terrain: "ASBS",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    iWeapons: ["Gatling Gun", "Graviton Cannon", "Fang Slasher", "Geist Knuckle", "G-Sword Diver"],
    weapons: []
  },
  AM_Gunner: {
    name: "AM Gunner",
    stats: [4400, 200, 130, 1100],
    upgrade: [8,8,5,9],
    move: 9,
    type: "Air",
    terrain: "SABS",
    size: "M",
    wpSpace: 10,
    partSlots: 3,
    fub: "EN +15%",
    abilities: ["G Territory"],
    iWeapons: ["Homing Missile", "Rip Missile", "G-Impact Cannon"],
    weapons: []
  }
};

var srg_dgg = {
  Grungust: {
    name: "Grungust",
    stats: [7500, 180, 75, 1800],
    upgrade: [5,5,10,5],
    move: 5,
    type: "Grd",
    terrain: "AAAA",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "All Weapons +200",
    abilities: ["Change: Wing Gust", "Change: Gust Lander"],
    iWeapons: ["Boost Knuckle", "Final Beam", "Calamity Sword", "Darkness Slash"],
    weapons: []
  },
  Wing_Gust: {
    name: "Wing Gust",
    stats: [7500, 180, 85, 1700],
    upgrade: [5,5,10,5],
    move: 7,
    type: "Air",
    terrain: "SBCS",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "All Weapons +200",
    abilities: ["Change: Grungust", "Change: Gust Lander"],
    iWeapons: ["Double Omega Laser", "Spiral Attack", "Missile"],
    weapons: []
  },
  Gust_Lander: {
    name: "Gust Lander",
    stats: [7500, 180, 70, 1900],
    upgrade: [5,5,10,5],
    move: 6,
    type: "Grd/Wtr",
    terrain: "ASAC",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "All Weapons +200",
    abilities: ["Change: Grungust", "Change: Wing Gust"],
    iWeapons: ["Missile", "Omega Cannon", "Drill Attack"],
    weapons: []
  },
  Grungust_2: {
    name: "Grungust Type 2",
    stats: [7000, 190, 85, 1700],
    upgrade: [6,6,10,6],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "TK Field absorb +300 damage",
    abilities: ["TK Field", "Change: G-Hawk"],
    iWeapons: ["Eye Laser", "Boost Knuckle", "Maxiblaster", "Doom Blade"],
    weapons: []
  },
  G_Hawk: {
    name: "G-Hawk",
    stats: [7000, 190, 95, 1600],
    upgrade: [6,6,10,6],
    move: 8,
    type: "Air",
    terrain: "SBCS",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "TK Field absorb +300 damage",
    abilities: ["TK Field", "Change: Grungust Type 2"],
    iWeapons: ["Eye Laser", "Split Missile", "Spiral Attack"],
    weapons: []
  },
  Grungust_3: {
    name: "Grungust Type 3",
    stats: [8300, 210, 90, 1800],
    upgrade: [5,5,10,5],
    move: 6,
    type: "Grd",
    terrain: "ASBA",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "All Weapons +200",
    abilities: [],
    iWeapons: ["Armor Breaker", "Eye Laser", "Drill Boost Knuckle", "Omega Blaster", "Sanshiki Zankantou: Ichimonjigiri"],
    weapons: []
  },
  Ryukooh: {
    name: "Ryukooh",
    stats: [8300, 210, 95, 1500],
    upgrade: [5,5,10,5],
    move: 6,
    type: "Air/Grd/Wtr",
    terrain: "SBAA",
    size: "L",
    wpSpace: 0,
    partSlots: 1,
    fub: "EN Regen (S)",
    abilities: ["TK Field", "HP Regen (S)", "Change: Koryuoh"],
    iWeapons: ["Bakuraifu", "Magma Burst", "Mountain Pressure", "Dragoon Blade", "Dragon Fang"],
    weapons: []
  },
  Koryuoh: {
    name: "Koryuoh",
    stats: [8300, 210, 115, 1300],
    upgrade: [5,5,10,5],
    move: 8,
    type: "Grd",
    terrain: "ASBA",
    size: "L",
    wpSpace: 0,
    partSlots: 1,
    fub: "EN Regen (S)",
    abilities: ["TK Field", "HP Regen (S)", "Double Image", "Change: Ryukooh"],
    iWeapons: ["Tiger Knuckle", "Random Spike", "Sonic Javelin", "Tyrant Breaker"],
    weapons: []
  },
  Dygenguard: {
    name: "Dygenguard",
    stats: [7800, 190, 100, 1900],
    upgrade: [5,5,10,5],
    move: 6,
    type: "Air/Grd",
    terrain: "ASBA",
    size: "L",
    wpSpace: 0,
    partSlots: 1,
    fub: "All Melee Weapons +200",
    abilities: [],
    iWeapons: ["Colossal Burst", "Colossal Spinner", "Colossal Thunder", "Colossal Storm"],
    weapons: []
  },
  Ausenseiter: {
    name: "Ausenseiter",
    stats: [7700, 190, 110, 1400],
    upgrade: [5,5,10,5],
    move: 8,
    type: "Air/Grd",
    terrain: "ASAA",
    size: "L",
    wpSpace: 0,
    partSlots: 1,
    fub: "All Ranged Weapons +200",
    abilities: [],
    iWeapons: ["Schulterplatte", "Lanzerkanone", "Sturmangriff",  "Lanzerganone W"],
    weapons: []
  }
};

var r_series = {
  R_1: {
    name: "R-1",
    stats: [3800, 120, 115, 1200],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Grd",
    terrain: "ASBA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Telekenesis Weapons +200",
    abilities: ["TK Field", "Change: R-Wing"],
    iWeapons: ["Gatling Gun", "T-Link Knuckle", "T-Link Sword"],
    weapons: ["Steel Knife", "G-Revovler", "Boosted Rifle"]
  },
  R_wing: {
    name: "R-Wing",
    stats: [3800, 120, 125, 1100],
    upgrade: [7,7,5,9],
    move: 8,
    type: "Air",
    terrain: "SBBA",
    size: "M",
    wpSpace: 0,
    partSlots: 2,
    fub: "Telekinesis Weapons +200",
    abilities: ["TK Field", "Change: R-1"],
    iWeapons: ["Anti-Air Missile", "Twin G-Cannon"],
    weapons: []
  },
  R_2: {
    name: "R-2 Powered",
    stats: [4600, 170, 100, 1700],
    upgrade: [6,7,8,7],
    move: 5,
    type: "Grd/Wtr",
    terrain: "AAAA",
    size: "M",
    wpSpace: 140,
    partSlots: 2,
    fub: "Ranged Weapons +200",
    abilities: ["AB Field"],
    iWeapons: ["Gatling Gun", "Beam Chakram", "Hi-Zol Launcher"],
    weapons: ["Beam Sword", "Magna Beam Rifle"]
  },
  R_3: {
    name: "R-3 Powered",
    stats: [4700, 140, 120, 1300],
    upgrade: [8,7,5,9],
    move: 7,
    type: "Air",
    terrain: "SABS",
    size: "M",
    wpSpace: 130,
    partSlots: 3,
    fub: "TK Field absorb +300 damage",
    abilities: ["Tk Field"],
    iWeapons: ["Gatling Gun", "TK Missile", "TK Laser Cannon", "Strike Shield"],
    weapons: ["Beam Sword"]
  },
  R_Gun: {
    name: "R-Gun Powered",
    stats: [3700, 180, 125, 1200],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Grd",
    terrain: "ASBS",
    size: "M",
    wpSpace: 120,
    partSlots: 3,
    fub: "EN +20%",
    abilities: ["TK Field"],
    iWeapons: ["Gatling Gun", "TK Boomerang", "Hyper Twin Launchers"],
    weapons: ["Double Magna Rifle"]
  },
  SRX: {
    name: "SRX",
    stats: [8200, 250, 85, 1800],
    upgrade: [5,5,8,9],
    move: 5,
    type: "Air/Grd",
    terrain: "SSAS",
    size: "L",
    wpSpace: 0,
    partSlots: 1,
    fub: "Part Slots +1",
    abilities: ["TK Field"],
    iWeapons: ["Finger Launcher", "Blade Kick", "Dominion Ball", "TK Burst Slash"],
    weapons: []
  }
};

var am = {
  Guarlion_Custom: {
    name: "Guarlion-Custom",
    stats: [3900, 130, 115, 1300],
    upgrade: [8,8,5,9],
    move: 7,
    type: "Air/Grd/Wtr",
    terrain: "SAAS",
    size: "M",
    wpSpace: 135,
    partSlots: 3,
    fub: "WP Space +30 and EN+10%",
    abilities: [],
    iWeapons: ["Autocannon", "Sonic Breaker"],
    weapons: ["Divine Blade", "Burst Railgun"]
  },
  Calion: {
    name: "Calion",
    stats: [3200, 120, 130, 900],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Air",
    terrain: "ABBS",
    size: "S",
    wpSpace: 10,
    partSlots: 3,
    fub: "Mobility +20%",
    abilities: [],
    iWeapons: ["Anti-Air Missile", "Sonic Cutter", "G-Drive"],
    weapons: []
  },
  Astelion: {
    name: "Astelion",
    stats: [4200, 140, 135, 1100],
    upgrade: [7,7,5,9],
    move: 8,
    type: "Air/Grd",
    terrain: "ABBS",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Mobilit +20%",
    abilities: [],
    iWeapons: ["Autocannon", "Sonic Breaker",  "RaMVs"],
    weapons: ["Assault Blade", "Burst Railgun"]
  },
  Fairlion_S: {
    name: "Fairlion-S",
    stats: [3300, 130, 130, 800],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Air/Grd",
    terrain: "SBCA",
    size: "S",
    wpSpace: 100,
    partSlots: 2,
    fub: "Mobility +20%",
    abilities: ["E Field", "Double Image", "Jammer"],
    iWeapons: ["Rolling Cannon", "Vostok Laser", "Sonic Driver"],
    weapons: ["Assault Blade"]
  },
  Fairlion_G: {
    name: "Fairlion-G",
    stats: [3300, 130, 130, 800],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Air/Grd",
    terrain: "SBCA",
    size: "S",
    wpSpace: 100,
    partSlots: 2,
    fub: "Mobility +20%",
    abilities: ["E Field", "Double Image", "Jammer"],
    iWeapons: ["Rolling Cannon", "Vostok Laser", "Sonic Driver"],
    weapons: ["Assault Blade"]
  },
  Valsione: {
    name: "Valsione",
    stats: [5300, 170, 120, 1300],
    upgrade: [6,5,6,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 110,
    partSlots: 2,
    fub: "Double Image activation +20%",
    abilities: ["Double Image"],
    iWeapons: ["Psy-Blaster", "Cross Smasher"],
    weapons: ["Divine Blade", "Magna Beam Cannon"]
  }
};

var shadow_mirrors = {
  Angelg: {
    name: "Angelg",
    stats: [6200, 180, 90, 1800],
    upgrade: [6,6,10,6],
    move: 7,
    type: "Air/Grd",
    terrain: "AABA",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "EN Regen (S)",
    abilities: ["Beam Coat", "Double Image"],
    iWeapons: ["Shadow Lance", "Mirage Sword", "Illusion Arrow", "Mirage Sign", "Phantom Phoenix"],
    weapons: []
  },
  Angelg_2: {
    name: "Angelg (Upgrade)",
    stats: [6200, 180, 90, 1800],
    upgrade: [6,6,10,6],
    move: 7,
    type: "Air/Grd",
    terrain: "AABA",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "EN Regen (S)",
    abilities: ["Beam Coat", "Double Image", "+200 Weapon Damage"],
    iWeapons: ["Shadow Lance", "Mirage Sword", "Illusion Arrow", "Mirage Sign", "Phantom Phoenix"],
    weapons: []
  },
  Vaisaga: {
    name: "Vaisaga",
    stats: [7000, 250, 120, 1900],
    upgrade: [6,6,10,6],
    move: 7,
    type: "Air/Grd",
    terrain: "SSAS",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "Double Image activation +20%",
    abilities: ["AB Field", "Double Image", "SplWpn Block"],
    iWeapons: ["Blazer Blades", "Flowing Claws", "Geo Splitter", "Gust Ripper", "Lite Saber"],
    weapons: []
  },
  Randgrith: {
    name: "Randgrith",
    stats: [5400, 140, 100, 1800],
    upgrade: [10,10,8,8],
    move: 6,
    type: "Grd/Wtr",
    terrain: "ASAA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "WP Space +30",
    abilities: ["Beam Coat", "Jammer"],
    iWeapons: ["Spider Net", "Phalanx Missile", "Matrix Missile", "Linear Bazooka"],
    weapons: ["Incision Knife", "M13 Shotgun"]
  },
  Rathgrith: {
    name: "Rathgrith",
    stats: [5600, 150, 105, 1900],
    upgrade: [7,7,8,7],
    move: 6,
    type: "Grd/Wtr",
    terrain: "ASAA",
    size: "M",
    wpSpace: 180,
    partSlots: 4,
    fub: "WP Space +50",
    abilities: ["Beam Coat", "Jammer"],
    iWeapons: ["Phalanx Missile", "Linear Missile Launcher", "Matrix Missile", "F-Solid Bazooka"],
    weapons: ["Incision Knife"]
  },
  Ashsaber: {
    name: "Ashsaber",
    stats: [3800, 190, 125, 1200],
    upgrade: [7,7,6,9],
    move: 8,
    type: "Grd",
    terrain: "ASAS",
    size: "M",
    wpSpace: 150,
    partSlots: 3,
    fub: "Ranged Weapons +200",
    abilities: ["Beam Coating", "Jammer"],
    iWeapons: ["Burning Dagger", "Halberd Shooter", "Sword Breakers"],
    weapons: ["Laser Blade", "Gun Rapier"]
  }
};

var misc = {
  Cybuster: {
    name: "Cybuster",
    stats: [5800, 180, 125, 1300],
    upgrade: [5,6,5,9],
    move: 7,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 0,
    partSlots: 2,
    fub: "Mobility +10% and EN +15%",
    abilities: ["Morale Block", "SP Block", "Change: Cybird"],
    iWeapons: ["Caloric Missile", "Cy-Flash", "High Familiar", "Zephyr Sword", "Akashic Buster", "Cosmo Nova"],
    weapons: []
  },
  Cybird: {
    name: "Cybird",
    stats: [5800, 180, 135, 1200],
    upgrade: [5,6,5,9],
    move: 9,
    type: "Air",
    terrain: "SBCS",
    size: "M",
    wpSpace: 0,
    partSlots: 2,
    fub: "Mobility +10% and EN +15%",
    abilities: ["Morale Block", "SP Block", "Change: Cybuster"],
    iWeapons: ["Cy-Flash", "Caloric Missile", "High Familiar"],
    weapons: []
  },
  Giganscudo_Duro: {
    name: "Giganscudo Duro",
    stats: [9000, 200, 70, 1900],
    upgrade: [4,6,10,5],
    move: 5,
    type: "Air/Grd",
    terrain: "AACS",
    size: "L",
    wpSpace: 0,
    partSlots: 2,
    fub: "Armor +10% and EN +15%",
    abilities: ["G Territory"],
    iWeapons: ["Weapon Breaker", "Giga Burst", "Giga Knuckle", "Giga Blaster", "Giga Unghia"],
    weapons: []
  },
  Lichkeit: {
    name: "Lichkeit",
    stats: [7800, 280, 135, 190],
    upgrade: [10,10,10,10],
    move: 7,
    type: "Air/Grd",
    terrain: "SSAS",
    size: "M",
    wpSpace: 0,
    partSlots: 1,
    fub: "Fixed Weapon Ground rating = S",
    abilities: ["Beam Coat", "HP Regen (S)", "EN Regen (S)", "Double Image", "Break Block"],
    iWeapons: ["Yomiji", "Mabuitachi", "Raigoue", "Mabuiguri"],
    weapons: []
  },
  F_32V: {
    name: "F-32V Schwert X",
    stats: [3000, 115, 115, 900],
    upgrade: [10,10,10,10],
    move: 7,
    type: "Air",
    terrain: "SBDA",
    size: "S",
    wpSpace: 10,
    partSlots: 3,
    fub: "Mobility +15%",
    abilities: [],
    iWeapons: ["Gatling Gun", "Anti-Air Missile"],
    weapons: []
  },
  Not_Gundam: {
    name: "Totally Not a Gundam",
    stats: [4000, 150, 120, 1000],
    upgrade: [9,9,9,9],
    move: 6,
    type: "Grd",
    terrain: "AAAA",
    size: "M",
    wpSpace: 100,
    partSlots: 4,
    fub: "+10% Armor, EN, Mobility, HP",
    abilities: [],
    iWeapons: ["Attack"],
    weapons: []
  }
};

module.exports = {
  battleships, ptx, rtx, srg_dgg, r_series, am, shadow_mirrors, misc
};