//stats [hp, en, mob, arm]
//upgrade [#hp, #en, #mob, #arm]

  var blank = {
    name: "",
    stats: [],
    upgrade: [],
    move: ,
    type: "",
    terrain: "",
    size: "",
    wpSpace: ,
    partSlots: ,
    fub: "",
    abilities: [],
    weapons: [],
    equipedWeapons: []
  }

var battleships = {
  Shirogane: {
    name: "Shirogane",
    stats: [14000, 200, 60, 1200],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    fub: "Armor +20%",
    wpSpace: 10,
    partSlots: 2,
    abilities: ["EN Regen (L)", "E Field"],
    weapons: ["AA Autocannon", "Spider Net", "Weaponbreaker", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon"],
    equipedWeapons: []
  },
  Hagane_1: {
    name: "Hagane (Shiro Type)",
    stats: [14000, 200, 60, 1200],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field"],
    weapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon"],
    equipedWeapons: []
  },
  Hagane_2: {
    name: "Hagane",
    stats: [15000,220,60,1230],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field'"],
    weapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Sub Cannon", "Impact Canon", "Tronium Cannon"],
    equipedWeapons: []
  },
  Kurogane: {
    name: "Kurogane",
    stats: [16000, 220, 65, 1500],
    upgrade: [4,5,10,9],
    move: 6,
    type: "Air/Wtr/UndGnd",
    terrain: "AAAA",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Armor +20%",
    abilities: ["E Field"],
    weapons: ["AA Autocannon", "Chaff Grenade", "Torpedo", "Homing Missile", "Sub Cannon", "Impact Cannon", "Titanic Drill"],
    equipedWeapons: []
  },
  Hiyru_Custom: {
    name: "Hiryu Custom",
    stats: [14000, 210, 65, 1300],
    upgrade: [4,6,10,9],
    move: 6,
    type: "Air/Wtr",
    terrain: "ABAS",
    size: "LL",
    wpSpace: 10,
    partSlots: 2,
    fub: "Weapon Accuracy +20%",
    abilities: ["E Field"],
    weapons: ["AA Autocannon", "Homing Missile", "Long Range Missile", "Dual Beam Cannon", "Gravity Cannon"],
    equipedWeapons: []
  }
}

var ptx = {
  Gespenst_Kai: {
    name: "Gespenst MKII-M (Kai)",
    stats: [3700, 100, 100, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd/Wtr",
    terrain: "AAAA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "All Terrains (except Air) S",
    abilities: [],
    weapons: ["Split Missile", "Jet Magnum"],
    equipedWeapons: ["M95 Machine Gun", "Plasma Slicer"]
  },
  Gespenst_Katina: {
    name: "Gespenst MKII-M (Katina)",
    stats: [3700, 100, 95, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "Armor and HP +15%",
    abilities: [],
    weapons: ["Split Missile", "Jet Magnum"],
    equipedWeapons: ["Plasma Slicer", "M13 Shotgun"]
  },
  Gespenst_Russel: {
    name: "Gespenst MKII-M (Russel)",
    stats: [3800, 100, 95, 1100],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "Armor +20%",
    abilities: [],
    weapons: ["Split Missile", "Jet Magnum"],
    equipedWeapons: ["M95 Machine Gun", "Plasma Slicer"]
  },
  Gespenst_R: {
    name: "Gespenst MkII-R",
    stats: [3700, 120, 110, 1200],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 180,
    partSlots: 4,
    fub: "Mobility +15% and HP +20%",
    abilities: ["Beam Coat"],
    weapons: ["Split Missile"],
    equipedWeapons: ["Plasma Cutter", "Chakram Caster", "Slash Ripper", "Double Magna Rifle", "Graviton Cannon"]
  },
  Gespenst_S: {
    name: "Gespenst MkII-S",
    stats: [4400, 200, 105, 1700],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Air/Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "HP +20% and EN +15%",
    abilities: ["AB Field"],
    weapons: ["Split Missile", "Mega Blaster", "Yell! Gespenst Kick!"],
    equipedWeapons: []
  },
  Gespenst: {
    name: "Gespenst",
    stats: [3600, 140, 110, 1200],
    upgrade: [10,10,8,10],
    move: 6,
    type: "Air/Grd/Wtr",
    terrain: "SSAS",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "I Weapon Ammo +4",
    abilities: ["Beam Coat"],
    weapons: ["Split Missile", "Neutron Beam"],
    equipedWeapons: ["Weapon Breaker", "Plasma Slicer", "Rectangle Launcher", "Remote Slasher", "M90 Assault Machine Gun"]
  },
  Alteisen: {
    name: "Alteisen",
    stats: [4500, 110, 95, 1600],
    upgrade: [6,8,8,7],
    move: 6,
    type: "Grd/Wtr",
    terrain: "ASAA",
    size: "M",
    wpSpace: 90,
    partSlots: 2,
    fub: "All Weapon Terrains S",
    abilities: ["Beam Coat"],
    weapons: ["Autocannon", "Heat Horn", "Revolver Stake", "Heavy Claymore", '"Trump Card"'],
    equipedWeapons: []
  },
  //need to check this, I think he has the wrong stats
  Alteisen_Reise: {
    name: "Alteisen Reise",
    stats: [6929, 130, 110, 1911],
    upgrade: [6, 8, 8, 7],
    move: 7,
    type: "Grd/Wtr",
    terrain: "ASAS",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "All Weapon Terrains S",
    abilities: ["Beam Coat"],
    weapons: ["5-Barrel Machine Cannon", "Plasma Horn", "Revolving Bunker", "Avalanche Claymore", "Aerial Claymore"],
    equipedWeapons: []
  },
  Weissritter: {
    name: "Wiessritter",
    stats: [4100, 120, 115, 900],
    upgrade: [8,8,5,10],
    move: 7,
    type: "Air/Grd",
    terrain: "AACS",
    size: "M",
    wpSpace: 90,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: ["Beam Coat"],
    weapons: ["Split Missile", "Beam Cannon", "Oxtongue Rifle E", "Oxtongue Rifile B", "Oxtongue Rifile W"],
    equipedWeapons: ["Plasma Slicer"]
  },
  Rein_Weissritter: {
    name: "Rein Weissritter",
    stats: [5100, 140, 125, 1100],
    upgrade: [8,8,5,10],
    move: 8,
    type: "Air/Grd",
    terrain: "SACS",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: ["Beam Coat", "HP Recovery (S)"],
    weapons: ["Split Missile", "3-Barrel Beam Cannon", "Howling Launcher E", "Howling Launher B", "Howling Launher X"],
    equipedWeapons: []
  },
  Schultzwald: {
    name: "Schultzwald",
    stats: [4400, 150, 85, 1600],
    upgrade: [10,10,10,10],
    move: 5,
    type: "Grd/Wtr",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "AB Field",
    abilities: [],
    weapons: ["Gatling Gun", "Autocannon", "Twin Geam Cannon"],
    equipedWeapons: ["Plasma Sliver", "G-Railgun"]
  },
  R_Blade: {
    name: "R-Blade",
    stats: [3500, 120, 115, 1200],
    upgrade: [7,8,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 170,
    partSlots: 4,
    fub: "W Space +30",
    abilities: [],
    weapons: ["Gatling Gun", "Blade Tonfa"],
    equipedWeapons: ["G-Revolver", "G-Railgun"]
  },
  Wildwurger: {
    name: "Wildwurger",
    stats: [4200, 150, 120, 1600],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 110,
    partSlots: 2,
    fub: "Mobility and Armor +15%",
    abilities: [],
    weapons: ["3-Barrel Gatling Cannon", "Cold Metal Sword", "Stag Beetle Crusher", "Raptor Wings"],
    equipedWeapons: ["M90 Assault Machine Gun"]
  },
  Wildwurger_L: {
    name: "Wildwurger-L",
    stats: [4200, 150, 120, 1600],
    upgrade: [10,10,10,10],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 140,
    partSlots: 3,
    fub: "Mobility and Armor +15%",
    abilities: [],
    weapons: ["Stun Shock", "3-Barrel Gatling Cannon", "M90 Assault Machine Gun", "Cold Metal Sword", "Stag Beetle Crusher", "Raptor Wings"],
    equipedWeapons: []
  },
  Wildfalken: {
    name: "Wildfalken",
    stats: [4000, 140, 130, 1100],
    upgrade: [7,7,5,9],
    move: 7,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 100,
    partSlots: 2,
    fub: "I Weapon Ammo +2",
    abilities: [],
    weapons: ["Gatling Gun", "Split Missile", "Oxtongue Rifle E", "Oxtongue Rifle B", "Oxtongue Rifle W"],
    equipedWeapons: ["Roche Saber"]
  }
};

var rtx = {
  Huckebein_II: {
    name: "Huckebein MKII",
    stats: [4000, 130, 115, 1200],
    upgrade: [8,9,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 3,
    fub: "W Space +50",
    abilities: ["G Wall"],
    weapons: ["Gatling Gun", "G-Impact Cannon"],
    equipedWeapons: ["Beam Sword" , "Photon Rifle", "Chakram Caster"]
  },
  Huckebein_IIM: {
    name: "Huckebein MkII-M",
    stats: [4000, 130, 115, 1200],
    upgrade: [8,9,6,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 3,
    fub: "W Space +30",
    abilities: [],
    weapons: ["Gatling Gun"],
    equipedWeapons: ["Beam Sword", "Photon Rifle", "Rectangle Launcher"]
  },
  Huckebein: {
    name: "Huckebein",
    stats: [3900, 150, 120, 1200],
    upgrade: [8,10,6,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 120,
    partSlots: 2,
    fub: "W Space +40 and EN +20%",
    abilities: ["AB Field", "Double Image"],
    weapons: ["Gatling Gun", "Black Hole Cannon"],
    equipedWeapons: ["Roche Saber", "Magna Beam Rifile", "Remote Slasher"]
  },
  Huckebein_III_L: {
    name: "Huckebein MIII-L",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Grd",
    terrain: "AABA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    weapons: ["Gatling Gun", "Multi-Trace Missiles", "Fang Slasher", "Graviton Rifle"],
    equipedWeapons: ["Roche Saber"]
  },
  Huckebein_III_T: {
    name: "Huckebeing MIII-T",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AAAA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    weapons: ["Gatling Gun", "Fang Slasher", "Graviton Rifle"],
    equipedWeapons: ["Roche Saber", "Remote Slasher", "Boosted Rifle"]
  },
  Huckebein_III_R: {
    name: "Huckebein MIII-R",
    stats: [4100, 160, 120, 1300],
    upgrade: [7,7,5,9],
    move: 6,
    type: "Air/Grd",
    terrain: "AAAA",
    size: "M",
    wpSpace: 130,
    partSlots: 2,
    fub: "Armor and EN +10%",
    abilities: ["G Territory", "Double Image"],
    weapons: ["Gatling Gun", "Multitrace Missile", "Fang Slasher", "Graviton Rifile"],
    equipedWeapons: ["Photon Rifle, Roche Saber, Remote Slasher, Boosted Rifle"]
  },
  
};