var blank = 
    {
      name: "",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: ,
      type: "",
      properties: [],
      damage: ,
      range: [],
      hit: ,
      terrain: "",
      ammo: ,
      en: ,
      crit: ,
      will: ,
      category: "",
      skill: "",
    };

var wp_spaec = [
  {
    name: "M95 Machine Gun",
    upgradeRate: "VF",
    upgradeCost: "VL",
    wpSpace: 15,
    type: "R",
    properties: ["P"],
    damage: 2300,
    range: [1,3],
    hit: 45,
    terrain: "AAAA",
    ammo: 20,
    en: 0,
    crit: 30,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "M13 Shotgun",
    upgradeRate: "F",
    upgradeCost: "L",
    wpSpace: 25,
    type: "R",
    properties: ["P"],
    damage: 2600,
    range: [2,3],
    hit: 60,
    terrain: "AAAA",
    ammo: 7,
    en: 0,
    crit: 55,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "Rectangle Launcher",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 40,
    type: "R",
    properties: [],
    damage: 3400,
    range: [2,7],
    hit: 20,
    terrain: "AABA",
    ammo: 6,
    en: 0,
    crit: 10,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "M90 Assault Machine Gun",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: ["P"],
    damage: 3900,
    range: [1,4],
    hit: 35,
    terrain: "AABA",
    ammo: 15,
    en: 0,
    crit: 35,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "Double Magna Rifle",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: ["P"],
    damage: 3400,
    range: [2,4],
    hit: 30,
    terrain: "AABA",
    ammo: 6,
    en: 0,
    crit: 15,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "Boosted Rifle",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: [],
    damage: 3200,
    range: [3,7],
    hit: 30,
    terrain: "AABA",
    ammo: 7,
    en: 0,
    crit: 35,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "G-Revolver",
    upgradeRate: "VF",
    upgradeCost: "VL",
    wpSpace: 15,
    type: "R",
    properties: ["P"],
    damage: 2500,
    range: [1,3],
    hit: 50,
    terrain: "ASAA",
    ammo: 6,
    en: 0,
    crit: 45,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "G-Railgun",
    upgradeRate: "M",
    upgradeCost: "L",
    wpSpace: 30,
    type: "R",
    properties: [],
    damage: 3000,
    range: [1,7],
    hit: 30,
    terrain: "AABA",
    ammo: 10,
    en: 0,
    crit: 20,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "Burst Railgun",
    upgradeRate: "M",
    upgradeCost: "L",
    wpSpace: 30,
    type: "R",
    properties: [],
    damage: 2900,
    range: [2,7],
    hit: 35,
    terrain: "SBAA",
    ammo: 10,
    en: 0,
    crit: 20,
    will: 0,
    category: "Bullet",
    skill: "",
  },
  {
    name: "Mega Beam Rifle",
    upgradeRate: "F",
    upgradeCost: "VL",
    wpSpace: 25,
    type: "R",
    properties: ["P"],
    damage: 2600,
    range: [2,4],
    hit: 35,
    terrain: "AADA",
    ammo: 12,
    en: 0,
    crit: 20,
    will: 0,
    category: "Energy Beam",
    skill: "",
  },
  {
    name: "Photon Rifle",
    upgradeRate: "F",
    upgradeCost: "L",
    wpSpace: 30,
    type: "R",
    properties: [],
    damage: 2800,
    range: [1,6],
    hit: 40,
    terrain: "AABA",
    ammo: 12,
    en: 0,
    crit: 20,
    will: 0,
    category: "Energy Beam",
    skill: "",
  },
  {
    name: "Magna Beam Rifle",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: [],
    damage: 3300,
    range: [2,7],
    hit: 25,
    terrain: "AADA",
    ammo: 8,
    en: 0,
    crit: 45,
    will: 0,
    category: "Energy Beam",
    skill: "",
  },
  {
    name: "Mega Beam Cannon",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: ["P"],
    damage: 3200,
    range: [1,4],
    hit: 20,
    terrain: "AADS",
    ammo: 0,
    en: 5,
    crit: 40,
    will: 0,
    category: "Energy Beam",
    skill: "",
  },
  {
    name: "Gun Rapier",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 40,
    type: "R",
    properties: ["P"],
    damage: 3500,
    range: [1,3],
    hit: 40,
    terrain: "ABA",
    ammo: 10,
    en: 0,
    crit: 10,
    will: 0,
    category: "Energy Beam",
    skill: "",
  },
  {
    name: "Steel Knife",
    upgradeRate: "VF",
    upgradeCost: "VL",
    wpSpace: 15,
    type: "M",
    properties: ["P"],
    damage: 2400,
    range: [1,1],
    hit: 50,
    terrain: "ASAA",
    ammo: 0,
    en: 0,
    crit: 50,
    will: 0,
    category: "Physical Blade",
    skill: "",
  },
  {
    name: "Divine Blade",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 30,
    type: "M",
    properties: ["P"],
    damage: 2900,
    range: [1,1],
    hit: 20,
    terrain: "SAAA",
    ammo: 0,
    en: 0,
    crit: 45,
    will: 0,
    category: "Physical Blade",
    skill: "",
  },
  {
    name: "Assault Blade",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 25,
    type: "M",
    properties: ["P"],
    damage: 2800,
    range: [1,2],
    hit: 30,
    terrain: "SBAA",
    ammo: 0,
    en: 0,
    crit: 40,
    will: 0,
    category: "Physical Blade",
    skill: "",
  },
  {
    name: "Shishioh Blade",
    upgradeRate: "S",
    upgradeCost: "H",
    wpSpace: 60,
    type: "M",
    properties: ["P"],
    damage: 4600,
    range: [1,1],
    hit: 50,
    terrain: "SSSS",
    ammo: 0,
    en: 0,
    crit: 40,
    will: 0,
    category: "Physical Blade",
    skill: "",
  },
  {
    name: "Plasma Sword",
    upgradeRate: "F",
    upgradeCost: "L",
    wpSpace: 25,
    type: "M",
    properties: ["P"],
    damage: 2600,
    range: [1,2],
    hit: 40,
    terrain: "AABA",
    ammo: 0,
    en: 5,
    crit: 30,
    will: 0,
    category: "Energy Blade",
    skill: "",
  },
  {
    name: "Beam Sword",
    upgradeRate: "VF",
    upgradeCost: "VL",
    wpSpace: 20,
    type: "M",
    properties: ["P"],
    damage: 2500,
    range: [1,1],
    hit: 45,
    terrain: "AABA",
    ammo: 0,
    en: 0,
    crit: 40,
    will: 0,
    category: "Energy Blade",
    skill: "",
  },
  {
    name: "Roche Saber",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 30,
    type: "M",
    properties: ["P"],
    damage: 3000,
    range: [1,2],
    hit: 10,
    terrain: "ASAS",
    ammo: 0,
    en: 10,
    crit: 0,
    will: 0,
    category: "Energy Blade",
    skill: "",
  },
  {
    name: "Laser Blade",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 30,
    type: "M",
    properties: ["P"],
    damage: 3000,
    range: [1,1],
    hit: 35,
    terrain: "AACA",
    ammo: 0,
    en: 5,
    crit: 45,
    will: 0,
    category: "Energy Blade",
    skill: "",
  },
  {
    name: "Remote Slasher",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 40,
    type: "R",
    properties: [],
    damage: 3500,
    range: [3,6],
    hit: 10,
    terrain: "AABA",
    ammo: 0,
    en: 0,
    crit: 0,
    will: 110,
    category: "Remote",
    skill: "",
  },
  {
    name: "Chakram Caster",
    upgradeRate: "M",
    upgradeCost: "L",
    wpSpace: 30,
    type: "M",
    properties: ["P"],
    damage: 2900,
    range: [2,4],
    hit: 35,
    terrain: "AABA",
    ammo: 0,
    en: 5,
    crit: 45,
    will: 0,
    category: "Remote",
    skill: "",
  },
  {
    name: "Slash Ripper",
    upgradeRate: "M",
    upgradeCost: "L",
    wpSpace: 30,
    type: "R",
    properties: ["P"],
    damage: 3000,
    range: [1,3],
    hit: 20,
    terrain: "AABA",
    ammo: 6,
    en: 0,
    crit: 35,
    will: 0,
    category: "Remote",
    skill: "",
  },
  {
    name: "Neo-Chakram Caster",
    upgradeRate: "M",
    upgradeCost: "H",
    wpSpace: 50,
    type: "M",
    properties: [],
    damage: 4300,
    range: [1,7],
    hit: 45,
    terrain: "SSSS",
    ammo: 0,
    en: 15,
    crit: 25,
    will: 0,
    category: "Remote",
    skill: "",
  },
  {
    name: "Incision Knife",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 20,
    type: "M",
    properties: ["P"],
    damage: 2800,
    range: [1,1],
    hit: 20,
    terrain: "ASAS",
    ammo: 0,
    en: 0,
    crit: 20,
    will: 0,
    category: "Physical",
    skill: "",
  },
  {
    name: "G-Impact Stake",
    upgradeRate: "S",
    upgradeCost: "H",
    wpSpace: 65,
    type: "M",
    properties: ["P"],
    damage: 4900,
    range: [1,3],
    hit: 35,
    terrain: "SSSS",
    ammo: 6,
    en: 0,
    crit: 70,
    will: 0,
    category: "Physical",
    skill: "",
  },
  {
    name: "Boosted Hammer",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 50,
    type: "M",
    properties: ["P"],
    damage: 4300,
    range: [1,4],
    hit: 40,
    terrain: "SSSS",
    ammo: 0,
    en: 5,
    crit: 70,
    will: 0,
    category: "Physical",
    skill: "",
  },
  {
    name: "Graviton Cannon",
    upgradeRate: "S",
    upgradeCost: "H",
    wpSpace: 60,
    type: "R",
    properties: [],
    damage: 5000,
    range: [2,8],
    hit: 20,
    terrain: "SSSS",
    ammo: 0,
    en: 40,
    crit: 10,
    will: 120,
    category: "Supreme",
    skill: "",
  },
  {
    name: "Linear Missile Launcher",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 35,
    type: "R",
    properties: [],
    damage: 3600,
    range: [1,6],
    hit: 50,
    terrain: "AABA",
    ammo: 15,
    en: 0,
    crit: 20,
    will: 0,
    category: "Missile",
    skill: "",
  },
  {
    name: "Stealth Wing",
    upgradeRate: "M",
    upgradeCost: "M",
    wpSpace: 40,
    type: "R",
    properties: ["P"],
    damage: 3900,
    range: [3,5],
    hit: 55,
    terrain: "SSSS",
    ammo: 0,
    en: 0,
    crit: 30,
    will: 0,
    category: "Remote",
    skill: "",
  },
  {
    name: "Mind Blast",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 35,
    type: "",
    properties: ["P"],
    damage: 1800,
    range: [1,4],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "Anti-Spirit",
    skill: "",
  },
  {
    name: "Spider Net",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 30,
    type: "",
    properties: ["P"],
    damage: 2000,
    range: [1,4],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "Net",
    skill: "",
  },
  {
    name: "Chaff Grenade",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 30,
    type: "",
    properties: [],
    damage: 2100,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "Hit Lower",
    skill: "",
  },
  {
    name: "Armor Breaker",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 40,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "Armor Break",
    skill: "",
  },
  {
    name: "Weapon Breaker",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 20,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "Weapon Break",
    skill: "",
  },
  {
    name: "Energy Taker",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 1700,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "EN Absorb",
    skill: "",
  },
  {
    name: "Energy Taker+",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,5],
    hit: 50,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 10,
    will: 0,
    category: "EN Absorb+",
    skill: "",
  },
  {
    name: "Energy Drain",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 1700,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "EN Drain",
    skill: "",
  },
  {
    name: "Energy Drain+",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,5],
    hit: 50,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 10,
    will: 0,
    category: "EN Drain+",
    skill: "",
  },
  {
    name: "Spirit Taker",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 1700,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "SP Absorb",
    skill: "",
  },
  {
    name: "Spirit Taker+",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,5],
    hit: 50,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 10,
    will: 0,
    category: "SP Absorb+",
    skill: "",
  },
  {
    name: "Spirit Drain",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 1700,
    range: [1,6],
    hit: 70,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 0,
    will: 0,
    category: "SP Drain",
    skill: "",
  },
  {
    name: "Energy SP+",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 15,
    type: "",
    properties: [],
    damage: 2000,
    range: [1,5],
    hit: 50,
    terrain: "AAAA",
    ammo: 2,
    en: 0,
    crit: 10,
    will: 0,
    category: "SP Drain+",
    skill: "",
  },
  {
    name: "Repair Module",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 5,
    type: "",
    properties: ["Repair"],
    damage: 0,
    range: [1,1],
    hit: 0,
    terrain: "DDDD",
    ammo: 1,
    en: 0,
    crit: 0,
    will: 0,
    category: "Repair",
    skill: "",
  },
  {
    name: "Supply Module",
    upgradeRate: "",
    upgradeCost: "",
    wpSpace: 5,
    type: "",
    properties: ["Supply"],
    damage: 0,
    range: [1,1],
    hit: 0,
    terrain: "DDDD",
    ammo: 1,
    en: 0,
    crit: 0,
    will: 0,
    category: "Supply",
    skill: "",
  }
  
];


var battleships_built_in = {
  Shirogane: [
    {
      name: "Anti-Air Autocannon",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2000,
      range: [1,2],
      hit: 20,
      terrain: "SBCS",
      ammo: 30,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Anti-Air Missile",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2800,
      range: [1,5],
      hit: 40,
      terrain: "SBBS",
      ammo: 20,
      en: 0,
      crit: 0,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Weapon Breaker",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2000,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Break",
      skill: "",
    },
    {
      name: "Spider Net",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: ["P"],
      damage: 2000,
      range: [1,4],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Net",
      skill: "",
    },
    {
      name: "Chaff Grenade",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2100,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Chaff",
      skill: "",
    },
    {
      name: "Torpedo",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2700,
      range: [2,7],
      hit: 35,
      terrain: "DDSD",
      ammo: 12,
      en: 0,
      crit: 50,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Sub Gun",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3300,
      range: [2,7],
      hit: 15,
      terrain: "AAAA",
      ammo: 10,
      en: 0,
      crit: 0,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Impact Cannon",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3800,
      range: [3,8],
      hit: 5,
      terrain: "AAAA",
      ammo: 0,
      en: 30,
      crit: 0,
      will: 0,
      category: "Supreme",
      skill: "",
    }
  ],
  Hagane_Shiro:[
    {
      name: "Chaff Grenade",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2100,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Chaff",
      skill: "",
    },
    {
      name: "Torpedo",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2700,
      range: [2,7],
      hit: 35,
      terrain: "DDSD",
      ammo: 12,
      en: 0,
      crit: 50,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Anti-Air Missile",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2900,
      range: [1,5],
      hit: 45,
      terrain: "SABS",
      ammo: 20,
      en: 0,
      crit: 0,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Sub Gun",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3500,
      range: [2,7],
      hit: 15,
      terrain: "AAAA",
      ammo: 10,
      en: 0,
      crit: 0,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Impact Cannon",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4000,
      range: [3,8],
      hit: 5,
      terrain: "AAAA",
      ammo: 0,
      en: 25,
      crit: 0,
      will: 0,
      category: "Supreme",
      skill: "",
    }
  ],
  Hagane: [
    {
      name: "Chaff Grenade",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2100,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Chaff",
      skill: "",
    },
    {
      name: "Anti-Air Autocannon",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2000,
      range: [1,2],
      hit: 20,
      terrain: "SBCS",
      ammo: 30,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Torpedo",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2700,
      range: [2,7],
      hit: 35,
      terrain: "DDSD",
      ammo: 12,
      en: 0,
      crit: 50,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Anti-Air Missile",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2900,
      range: [1,5],
      hit: 45,
      terrain: "SABS",
      ammo: 20,
      en: 0,
      crit: 0,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Sub Gun",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3500,
      range: [2,7],
      hit: 15,
      terrain: "AAAA",
      ammo: 10,
      en: 0,
      crit: 0,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Impact Cannon",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4000,
      range: [3,8],
      hit: 5,
      terrain: "AAAA",
      ammo: 0,
      en: 25,
      crit: 0,
      will: 0,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Tronium Cannon",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 5900,
      range: [3,9],
      hit: 15,
      terrain: "SSAS",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 140,
      category: "Supreme",
      skill: "",
    }
  ],
  Kurogane: [
    {
      name: "Chaff Grenade",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2100,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Chaff",
      skill: "",
    },
    {
      name: "Anti-Air Autocannon",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2000,
      range: [1,2],
      hit: 20,
      terrain: "SBCS",
      ammo: 30,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Torpedo",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2900,
      range: [2,7],
      hit: 35,
      terrain: "DDSD",
      ammo: 12,
      en: 0,
      crit: 50,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Anti-Air Missile",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3100,
      range: [1,5],
      hit: 45,
      terrain: "SABS",
      ammo: 20,
      en: 0,
      crit: 0,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Sub Gun",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3700,
      range: [2,7],
      hit: 15,
      terrain: "AAAA",
      ammo: 10,
      en: 0,
      crit: 0,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Impact Cannon",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4200,
      range: [3,8],
      hit: 5,
      terrain: "AAAA",
      ammo: 0,
      en: 25,
      crit: 0,
      will: 0,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Titanic Drill",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 6100,
      range: [1,4],
      hit: 40,
      terrain: "SSSS",
      ammo: 0,
      en: 70,
      crit: 10,
      will: 130,
      category: "Supreme",
      skill: "",
    }
  ],
  Hiryu: [
    {
      name: "Chaff Grenade",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 2100,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Chaff",
      skill: "",
    },
    {
      name: "Anti-Air Autocannon",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2000,
      range: [1,2],
      hit: 30,
      terrain: "SBCS",
      ammo: 30,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Anti-Air Missile",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2700,
      range: [2,4],
      hit: 40,
      terrain: "SABS",
      ammo: 15,
      en: 0,
      crit: 0,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Long Range Missile",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3500,
      range: [1,6],
      hit: 25,
      terrain: "SAAS",
      ammo: 10,
      en: 0,
      crit: 45,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Dual Beam Cannon",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3700,
      range: [2,8],
      hit: 20,
      terrain: "AACS",
      ammo: 0,
      en: 20,
      crit: 0,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Gravity Cannon",
      upgradeRate: "M",
      upgradeCost: "H",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 5000,
      range: [2,9],
      hit: 15,
      terrain: "SSSS",
      ammo: 0,
      en: 80,
      crit: 5,
      will: 130,
      category: "Supreme",
      skill: "",
    }
  ]
};

var ptx_built_in = {
  Gespenst_Kai: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2200,
      range: [1,6],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 20,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Jet Magnum",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P", "C"],
      damage: 3500,
      range: [1,2],
      hit: 35,
      terrain: "BAAA",
      ammo: 0,
      en: 10,
      crit: 30,
      will: 105,
      category: "Physical",
      skill: "",
    }
  ],
  Gespenst_Katina: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2500,
      range: [1,6],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 20,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Jet Magnum",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P", "C"],
      damage: 3500,
      range: [1,2],
      hit: 35,
      terrain: "BAAA",
      ammo: 0,
      en: 10,
      crit: 30,
      will: 105,
      category: "Physical",
      skill: "",
    }
  ],
  Gespenst_Russel: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2000,
      range: [1,6],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Jet Magnum",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P", "C"],
      damage: 3500,
      range: [1,2],
      hit: 35,
      terrain: "BAAA",
      ammo: 0,
      en: 10,
      crit: 15,
      will: 105,
      category: "Physical",
      skill: "",
    }
  ],
  Gespenst_R: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2200,
      range: [1,7],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    }
  ],
  Gespenst_S: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3000,
      range: [1,6],
      hit: 45,
      terrain: "BAAA",
      ammo: 20,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Mega Blaster",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 4400,
      range: [1,4],
      hit: 40,
      terrain: "SSAS",
      ammo: 0,
      en: 15,
      crit: 20,
      will: 0,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Gespy Kick!",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: ["P", "C"],
      damage: 5000,
      range: [1,2],
      hit: 35,
      terrain: "SSAS",
      ammo: 0,
      en: 30,
      crit: 65,
      will: 0,
      category: "Supreme",
      skill: "",
    }
  ],
  Gespenst: [
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2300,
      range: [1,6],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Neutron Beam",
      upgradeRate: "F",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3800,
      range: [1,6],
      hit: 35,
      terrain: "SSAS",
      ammo: 10,
      en: 0,
      crit: 0,
      will: 0,
      category: "Energy Beam",
      skill: "",
    }
  ],
  Alteisen: [
    {
      name: "Autocannon",
      upgradeRate: "M",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2300,
      range: [2,4],
      hit: 30,
      terrain: "AAAA",
      ammo: 10,
      en: 0,
      crit: 10,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Heat Horn",
      upgradeRate: "M",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 2400,
      range: [1,1],
      hit: 40,
      terrain: "AABA",
      ammo: 0,
      en: 0,
      crit: 40,
      will: 0,
      category: "Physical",
      skill: "",
    },
    {
      name: "Revolver Stake",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 3600,
      range: [1,3],
      hit: 10,
      terrain: "ABA",
      ammo: 6,
      en: 0,
      crit: 35,
      will: 0,
      category: "Physical",
      skill: "",
    },
    {
      name: "Heavy Claymore",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: [],
      damage: 4200,
      range: [1,2],
      hit: 50,
      terrain: "AAAA",
      ammo: 4,
      en: 0,
      crit: 50,
      will: 110,
      category: "Supreme",
      skill: "",
    },
    {
      name: "\"Trump Card\"",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "M",
      properties: [],
      damage: 5200,
      range: [1],
      hit: 40,
      terrain: "BSBS",
      ammo: 1,
      en: 0,
      crit: 45,
      will: 130,
      category: "",
      skill: "",
    }
  ],
  Alteisen_Riese: [
    {
      name: "Chain Gun",
      upgradeRate: "M",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2700,
      range: [2,4],
      hit: 30,
      terrain: "AAAA",
      ammo: 15,
      en: 0,
      crit: 10,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Plasma Horn",
      upgradeRate: "M",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 2800,
      range: [1,1],
      hit: 40,
      terrain: "AABA",
      ammo: 0,
      en: 0,
      crit: 40,
      will: 0,
      category: "Physical",
      skill: "",
    },
    {
      name: "Revolver Bunker",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 4000,
      range: [1,3],
      hit: 10,
      terrain: "ABA",
      ammo: 6,
      en: 0,
      crit: 35,
      will: 0,
      category: "Physical",
      skill: "",
    },
    {
      name: "Claymore Avalanche",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: [],
      damage: 4800,
      range: [1,2],
      hit: 50,
      terrain: "AAAA",
      ammo: 8,
      en: 0,
      crit: 50,
      will: 110,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Claymore Overlord",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "M",
      properties: [],
      damage: 5800,
      range: [1],
      hit: 40,
      terrain: "ASAS",
      ammo: 2,
      en: 0,
      crit: 45,
      will: 130,
      category: "",
      skill: "",
    }
  ],
  Weissritter: [
    {
      name: "Triple Beam Cannon",
      upgradeRate: "F",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2400,
      range: [1,3],
      hit: 40,
      terrain: "ABDS",
      ammo: 10,
      en: 0,
      crit: 20,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2200,
      range: [1,5],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Oxtongue Rifle B",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3800,
      range: [2,6],
      hit: 30,
      terrain: "AAAS",
      ammo: 7,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Oxtongue Rifle E",
      upgradeRate: "F",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3500,
      range: [4,8],
      hit: 35,
      terrain: "ABDS",
      ammo: 0,
      en: 15,
      crit: 0,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Oxtongue Rifle D",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4500,
      range: [3,7],
      hit: 40,
      terrain: "SBBS",
      ammo: 3,
      en: 0,
      crit: 30,
      will: 130,
      category: "Supreme",
      skill: "",
    }
  ],
  Rein_Weissritter: [
    {
      name: "Triple Beam Cannon",
      upgradeRate: "F",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 3300,
      range: [1,4],
      hit: 40,
      terrain: "ABDS",
      ammo: 10,
      en: 0,
      crit: 20,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Split Missile",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2800,
      range: [1,5],
      hit: 45,
      terrain: "BAAA",
      ammo: 12,
      en: 0,
      crit: 30,
      will: 0,
      category: "Missile",
      skill: "",
    },
    {
      name: "Howling Rifle B",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4300,
      range: [2,6],
      hit: 30,
      terrain: "AAAS",
      ammo: 8,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Howling Rifle E",
      upgradeRate: "F",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4100,
      range: [3,8],
      hit: 35,
      terrain: "ABDS",
      ammo: 0,
      en: 20,
      crit: 0,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Howling Rifle X",
      upgradeRate: "F",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 5100,
      range: [1,8],
      hit: 40,
      terrain: "SBBS",
      ammo: 0,
      en: 50,
      crit: 30,
      will: 130,
      category: "Energy Beam",
      skill: "",
    }
  ],
  Schutzwald: [
    {
      name: "Gatling Gun",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 1200,
      range: [1,1],
      hit: 40,
      terrain: "AAAA",
      ammo: 20,
      en: 0,
      crit: 35,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Autocannon",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 2700,
      range: [1,4],
      hit: 35,
      terrain: "AAAA",
      ammo: 12,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Twin Beam Cannon",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3600,
      range: [2,7],
      hit: 30,
      terrain: "AADA",
      ammo: 0,
      en: 25,
      crit: 10,
      will: 0,
      category: "Energy Beam",
      skill: "",
    }
  ],
  R_Blade: [
    {
      name: "Gatling Gun",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 1000,
      range: [1,1],
      hit: 30,
      terrain: "AAAA",
      ammo: 20,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Blade Tonfa",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "M",
      properties: ["P", "C"],
      damage: 3600,
      range: [1,4],
      hit: 40,
      terrain: "AAAA",
      ammo: 0,
      en: 0,
      crit: 35,
      will: 105,
      category: "Supreme",
      skill: "",
    }
  ],
  Wildwurger: [
    {
      name: "Triple Vulcan",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2900,
      range: [1,4],
      hit: 35,
      terrain: "AABA",
      ammo: 20,
      en: 0,
      crit: 10,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Metal Sword",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 3500,
      range: [1,2],
      hit: 40,
      terrain: "AABA",
      ammo: 0,
      en: 0,
      crit: 40,
      will: 0,
      category: "Physical Blade",
      skill: "",
    },
    {
      name: "Beetle Crusher",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 4000,
      range: [1,1],
      hit: 30,
      terrain: "AABA",
      ammo: 0,
      en: 5,
      crit: 45,
      will: 0,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Raptor Wings",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 4700,
      range: [1,3],
      hit: 25,
      terrain: "AABA",
      ammo: 0,
      en: 35,
      crit: 55,
      will: 120,
      category: "Supreme",
      skill: "",
    }
  ],
  Wildwurger_L: [
    {
      name: "Stun Shot",
      upgradeRate: "",
      upgradeCost: "",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 1800,
      range: [1,6],
      hit: 70,
      terrain: "AAAA",
      ammo: 1,
      en: 0,
      crit: 0,
      will: 0,
      category: "Anti-Spirit",
      skill: "",
    },
    {
      name: "M90 Assault Rifle",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 3400,
      range: [1,4],
      hit: 35,
      terrain: "AABA",
      ammo: 15,
      en: 0,
      crit: 35,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Triple Vulcan",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 2900,
      range: [1,4],
      hit: 35,
      terrain: "AABA",
      ammo: 20,
      en: 0,
      crit: 10,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Metal Sword",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 3500,
      range: [1,2],
      hit: 40,
      terrain: "AABA",
      ammo: 0,
      en: 0,
      crit: 40,
      will: 0,
      category: "Physical Blade",
      skill: "",
    },
    {
      name: "Beetle Crusher",
      upgradeRate: "M",
      upgradeCost: "L",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 4000,
      range: [1,1],
      hit: 30,
      terrain: "AABA",
      ammo: 0,
      en: 5,
      crit: 45,
      will: 0,
      category: "Supreme",
      skill: "",
    },
    {
      name: "Raptor Wings",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "M",
      properties: ["P"],
      damage: 4700,
      range: [1,3],
      hit: 25,
      terrain: "AABA",
      ammo: 0,
      en: 35,
      crit: 55,
      will: 120,
      category: "Supreme",
      skill: "",
    }
  ],
  Wildfalken: [
    {
      name: "Gatling Gun",
      upgradeRate: "VF",
      upgradeCost: "VL",
      wpSpace: 0,
      type: "R",
      properties: ["P"],
      damage: 1200,
      range: [1,1],
      hit: 30,
      terrain: "AAAA",
      ammo: 20,
      en: 0,
      crit: 30,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Split Missile+",
      upgradeRate: "VS",
      upgradeCost: "VH",
      wpSpace: 0,
      type: "R",
      properties: ["MAP"],
      damage: 2000,
      range: [2,6],
      hit: 20,
      terrain: "BAAA",
      ammo: 2,
      en: 0,
      crit: 0,
      will: 0,
      category: "Map",
      skill: "",
    },
    {
      name: "Oxtongue Rifle E",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 3800,
      range: [3,7],
      hit: 35,
      terrain: "ABDS",
      ammo: 0,
      en: 10,
      crit: 45,
      will: 0,
      category: "Energy Beam",
      skill: "",
    },
    {
      name: "Oxtongue Rifle B",
      upgradeRate: "M",
      upgradeCost: "M",
      wpSpace: 0,
      type: "R",
      properties: [],
      damage: 4000,
      range: [1,6],
      hit: 30,
      terrain: "AAAS",
      ammo: 6,
      en: 0,
      crit: 20,
      will: 0,
      category: "Bullet",
      skill: "",
    },
    {
      name: "Oxtongue Rifle D",
      upgradeRate: "S",
      upgradeCost: "H",
      wpSpace: 0,
      type: "",
      properties: [],
      damage: 4700,
      range: [2,8],
      hit: 40,
      terrain: "SBBS",
      ammo: 4,
      en: 0,
      crit: 30,
      will: 120,
      category: "Supreme",
      skill: "",
    }
  ]
};